version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pmarket
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend-api:
    build: ../backend-api
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://user:pass@db:5432/pmarket
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET: change_me
    depends_on: [db, redis]
    ports:
      - "3000:3000"

  wallet-service:
    build: ../wallet-service
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/pmarket
      WALLET_PORT: 3010
    depends_on: [db]
    ports:
      - "3010:3010"

  game-service:
    build: ../game-service
    environment:
      GAME_PORT: 3020
    ports:
      - "3020:3020"

  ai-engine:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ../ai-engine:/app
    command: bash -lc "pip install -r requirements.txt || true; pip install fastapi uvicorn scikit-learn lightgbm; uvicorn main:app --host 0.0.0.0 --port 8001"
    ports:
      - "8001:8001"

  linera-watcher:
    build:
      context: ../linera-watcher
      dockerfile: Dockerfile
    environment:
      WEBHOOK: http://backend-api:3000/webhook/linera/deposit-notify
    depends_on: [backend-api]

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../games/aviator:/usr/share/nginx/html/aviator:ro
      - ../games/mines:/usr/share/nginx/html/mines:ro
    depends_on: [backend-api]
    ports:
      - "80:80"

volumes:
  db_data: {}
