version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pln
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend-api:
    image: python:3.11-slim
    working_dir: /app
    command: bash -lc "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8002"
    volumes:
      - ../backend/api:/app
      - ../models:/models
    environment:
      DB_URL: postgresql://user:pass@db:5432/pln
      REDIS_URL: redis://redis:6379/0
      MODEL_STORE: /models
      COINGECKO_URL: https://api.coingecko.com/api/v3
    depends_on:
      - db
      - redis
    ports:
      - "8002:8002"

  bridge:
    image: node:20-alpine
    working_dir: /app
    command: sh -lc "npm ci || npm i && npm run dev"
    volumes:
      - ../backend/bridge:/app
    environment:
      LINERA_NODE_URL: http://linera-local:19100
      PREDICTION_CHAIN_ID: local-prediction
      AGGREGATOR_CHAIN_ID: local-aggregator
      TOKEN_CHAIN_ID: local-token
    depends_on:
      - backend-api

  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -lc "npm ci || npm i && npm run dev -- --host --port 3002"
    volumes:
      - ../frontend:/app
    ports:
      - "3002:3002"
    environment:
      VITE_LINERA_NODE_URL: http://localhost:19100

  linera-local:
    image: alpine:3.19
    command: ["sh","-lc","echo 'Placeholder Linera localnet. Replace with real image when available.' && sleep 3600"]

volumes:
  db_data: {}
